name: Lambda Checker

on:
  push:
    branches:
      - main  # Adjust this if you're using a different main branch name

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: make file exe
      run: |
      set -x
      chmod u+x ./Lambda-Check  # Print directory contents for debugging
      
    - name: Run Lambda Checker
      run: ./Lambda-Check
